name: ClusterFuzzLite continuous builds
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Use your actual default branch here.
permissions: 
  actions: read
jobs:
  Build:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       sanitizer: [address, undefined, memory]  # Override this with the sanitizers you want.
   steps:
   - name: Build Fuzzers (${{ matrix.sanitizer }})
     id: build
     uses: google/clusterfuzzlite/actions/build_fuzzers@v1
     with:
       sanitizer: ${{ matrix.sanitizer }}
       upload-build: true
